In [10]:
import json
for i in range(5):

    with open(f"mawps/Fold_{i}/test_mawps_new_mwpss_fold_{i}.json", 'r') as f:
        data = json.load(f)
    right = 0
    for item in data:
        for i in item["num_codes"].values():
            temp = set(i)
            if len(temp) != len(i):
                right+=1
                break
    print(right,len(data))

25 433
27 433
23 433
24 433
22 431


In [8]:
import torch
import torch.nn as nn

# 随机生成预测值和标签
predictions = torch.Tensor([0.5,0,0,0])  # 假设有4个样本, 输出值在0-1之间
labels = torch.Tensor([1, 0, 1, 0])  # 真实的标签

# 创建损失函数
criterion = nn.BCEWithLogitsLoss()

# 计算损失
loss = criterion(predictions[1,0,0,0], labels[1,0,0,0])
print(loss)


IndexError: too many indices for tensor of dimension 1

In [6]:
import numpy as np

# 假设你的数组是这样的
num_codes_labels = np.array([0.5, 1.5, 2, 0.2, 1.7])
outputs = np.array([0.4, 0.6, 0.7, 0.5, 0.4])
# 找出num_codes_labels中大于1的位置
greater_than_one = num_codes_labels > 1
# 找出outputs中大于0.5的位置
greater_than_half = outputs > 0.5
# 找出同时满足两个条件的位置
both_conditions = np.logical_and(greater_than_one, greater_than_half)
# 打印结果
indices = np.where(both_conditions)
outputs[indices]=num_codes_labels[indices]

[False  True  True False False]
(array([1, 2]),)
[0.4 1.5 2.  0.5 0.4]


In [9]:
import numpy as np

numbers = np.array([[0.1, 0.3, 0.2, 0.55],
                    [0.4, 0.7, 0.8, 0.2],
                    [0.9, 0.5, 0.3, 0.1],
                    [0.2, 0.6, 0.4, 0.8]])

# 从大于0.5的数值中找到最小值
min_value = np.min(numbers[numbers > 0.5])

# 找到最小值的位置
indices = np.where(numbers == min_value)

print(indices[0])
print(min_value)

[0]
0.55


In [8]:
import torch

outputs_rounded = torch.tensor([[[0, 1, 0], [1, 0, 0]], [[1, 0, 0], [0, 1, 0]]])
labels = torch.tensor([[[0, 1, 0], [1, 0, 0]], [[0, 0, 1], [1, 0, 0]]])

# 判断最后一个维度是否相等
equality = torch.eq(outputs_rounded[:, :, -1:], labels[:, :, -1:])

print(equality)


tensor([[[ True],
         [ True]],

        [[False],
         [ True]]])


In [13]:
A = torch.tensor([[[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]])
B = torch.tensor([[[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]])
equality = torch.eq(A, B)
equal = torch.all(equality, dim=-1, keepdim=True)
print(equal)

tensor([[[ True],
         [ True],
         [ True],
         [False]]])


In [2]:
import torch
import torch.nn as nn

# 随机生成预测值和标签
predictions = torch.Tensor([0.5,0,1,0])  # 假设有4个样本, 输出值在0-1之间
labels = torch.Tensor([1, 0, 1, 0])  # 真实的标签

outpus_processed = 1 - 2 * torch.abs(0.5 - predictions)

print(predictions)
print(outpus_processed)


tensor([0.5000, 0.0000, 1.0000, 0.0000])
tensor([1., 0., 0., 0.])


In [13]:
def compute_iterations(P, alpha, beta, threshold):
    iterations = 1
    while P < threshold:
        P = P * alpha + P * (1-alpha) * beta + (1 - P) * alpha * beta
        iterations += 1
    return iterations

# 设定初始条件
P = 0.8
alpha = 0.89
beta = 0.8
threshold = 0.97

# 计算需要的迭代次数
iterations = compute_iterations(P, alpha, beta, threshold)
print("需要的迭代次数是：", iterations)


需要的迭代次数是： 8


In [ ]:
import numpy as np
def compute_iterations(P, alpha, beta, threshold):
    iterations = 0
    while P < threshold:
        P = P * alpha + P * (1-alpha) * beta + (1 - P) * alpha * beta
        iterations += 1
    return iterations

P = 0.88
threshold = 0.95
max_iterations = 10

# 初始的最小值为1，因为α和β的最大可能值为1
min_alpha = 1
min_beta = 1

step = 0.5  # 调整步长以改变搜索的精度和速度

# 对每一个可能的α和β值进行搜索
for alpha in np.arange(0.5, 1+step, step):
    for beta in np.arange(0.5, 1+step, step):
        iterations = compute_iterations(P, alpha, beta, threshold)
        # 如果在指定的迭代次数内达到阈值，并且α和β的值比当前找到的最小值还要小，那么就更新最小值
        if iterations <= max_iterations and alpha * beta < min_alpha * min_beta:
            min_alpha = alpha
            min_beta = beta

print("最小的α值为：", min_alpha)
print("最小的β值为：", min_beta)


: 

In [2]:
from transformers import T5Tokenizer, T5Model

tokenizer = T5Tokenizer.from_pretrained("google/flan-t5-large")
model = T5Model.from_pretrained("google/flan-t5-large")

input_ids = tokenizer(
    "Studies have been shown that owning a dog is good for you", return_tensors="pt"
).input_ids  # Batch size 1
decoder_input_ids = tokenizer("Studies show that", return_tensors="pt").input_ids  # Batch size 1

# forward pass
outputs = model(input_ids=input_ids, decoder_input_ids=decoder_input_ids)
last_hidden_states = outputs.last_hidden_state


ImportError: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html