In [10]:
import json
for i in range(5):

    with open(f"mawps/Fold_{i}/test_mawps_new_mwpss_fold_{i}.json", 'r') as f:
        data = json.load(f)
    right = 0
    for item in data:
        for i in item["num_codes"].values():
            temp = set(i)
            if len(temp) != len(i):
                right+=1
                break
    print(right,len(data))

25 433
27 433
23 433
24 433
22 431


In [8]:
import torch
import torch.nn as nn

# 随机生成预测值和标签
predictions = torch.Tensor([0.5,0,0,0])  # 假设有4个样本, 输出值在0-1之间
labels = torch.Tensor([1, 0, 1, 0])  # 真实的标签

# 创建损失函数
criterion = nn.BCEWithLogitsLoss()

# 计算损失
loss = criterion(predictions[1,0,0,0], labels[1,0,0,0])
print(loss)


IndexError: too many indices for tensor of dimension 1

In [6]:
import numpy as np

# 假设你的数组是这样的
num_codes_labels = np.array([0.5, 1.5, 2, 0.2, 1.7])
outputs = np.array([0.4, 0.6, 0.7, 0.5, 0.4])
# 找出num_codes_labels中大于1的位置
greater_than_one = num_codes_labels > 1
# 找出outputs中大于0.5的位置
greater_than_half = outputs > 0.5
# 找出同时满足两个条件的位置
both_conditions = np.logical_and(greater_than_one, greater_than_half)
# 打印结果
indices = np.where(both_conditions)
outputs[indices]=num_codes_labels[indices]

[False  True  True False False]
(array([1, 2]),)
[0.4 1.5 2.  0.5 0.4]


In [9]:
import numpy as np

numbers = np.array([[0.1, 0.3, 0.2, 0.55],
                    [0.4, 0.7, 0.8, 0.2],
                    [0.9, 0.5, 0.3, 0.1],
                    [0.2, 0.6, 0.4, 0.8]])

# 从大于0.5的数值中找到最小值
min_value = np.min(numbers[numbers > 0.5])

# 找到最小值的位置
indices = np.where(numbers == min_value)

print(indices[0])
print(min_value)

[0]
0.55


In [8]:
import torch

outputs_rounded = torch.tensor([[[0, 1, 0], [1, 0, 0]], [[1, 0, 0], [0, 1, 0]]])
labels = torch.tensor([[[0, 1, 0], [1, 0, 0]], [[0, 0, 1], [1, 0, 0]]])

# 判断最后一个维度是否相等
equality = torch.eq(outputs_rounded[:, :, -1:], labels[:, :, -1:])

print(equality)


tensor([[[ True],
         [ True]],

        [[False],
         [ True]]])


In [13]:
A = torch.tensor([[[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]])
B = torch.tensor([[[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]])
equality = torch.eq(A, B)
equal = torch.all(equality, dim=-1, keepdim=True)
print(equal)

tensor([[[ True],
         [ True],
         [ True],
         [False]]])


In [2]:
import torch
import torch.nn as nn

# 随机生成预测值和标签
predictions = torch.Tensor([0.5,0,1,0])  # 假设有4个样本, 输出值在0-1之间
labels = torch.Tensor([1, 0, 1, 0])  # 真实的标签

outpus_processed = 1 - 2 * torch.abs(0.5 - predictions)

print(predictions)
print(outpus_processed)


tensor([0.5000, 0.0000, 1.0000, 0.0000])
tensor([1., 0., 0., 0.])
