In [5]:
import torch

/data/zhyma/miniconda3/lib/python3.8/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [8]:
A = torch.arange(24).reshape(2,3,4)
b = torch.zeros(4)
A.index_fill_(1,torch.LongTensor([0,2]),0)
print(A)

tensor([[[ 0,  0,  0,  0],
         [ 4,  5,  6,  7],
         [ 0,  0,  0,  0]],

        [[ 0,  0,  0,  0],
         [16, 17, 18, 19],
         [ 0,  0,  0,  0]]])


In [2]:
import random
X = random.sample((range(10)),5)
print(X)

[6, 3, 5, 7, 0]


In [11]:
z = torch.Tensor([0]).squeeze()
print(z)

tensor(0.)


In [6]:
import torch.nn as nn
import torch

x = torch.randn((2, 2))
y = torch.tensor([0, -1])
# 不添加ignore_index
ce = nn.CrossEntropyLoss(reduction='none')
# 添加ignore_index
ce_i = nn.CrossEntropyLoss(ignore_index = -1, reduction='none')
# out = ce(x, y)
out_i = ce_i(x, y)
print(x)
print(y)
print(out_i)


tensor([[-0.7155,  1.1286],
        [ 0.2429,  1.0069]])
tensor([ 0, -1])
tensor([1.9910, 0.0000])


In [16]:
import torch

A = torch.rand((4,3,2))
mask = torch.zeros((4,3,1))
print(A)
is_wrong = (A[:,:,0]>A[:,:,1]).unsqueeze(-1)
# print(is_wrong) 
is_wrong = is_wrong & is_wrong
# print(is_wrong)
mask.masked_fill_(is_wrong,torch.scalar_tensor(1))
print(mask)

tensor([[[0.3795, 0.3344],
         [0.7015, 0.5201],
         [0.7108, 0.6544]],

        [[0.2516, 0.9643],
         [0.8875, 0.6337],
         [0.2419, 0.8269]],

        [[0.5955, 0.6044],
         [0.1963, 0.9599],
         [0.5264, 0.9293]],

        [[0.0913, 0.7024],
         [0.6310, 0.8447],
         [0.9335, 0.4806]]])
tensor([[[1.],
         [1.],
         [1.]],

        [[0.],
         [1.],
         [0.]],

        [[0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [1.]]])


In [7]:
import torch
A = torch.arange(6).reshape(2,3).float()
B = torch.rand((2,3))
C = torch.tensor([
    [True,False,False],
    [False,False,True]
])
A[C]=B[C]
print(A)

tensor([[0.9133, 1.0000, 2.0000],
        [3.0000, 4.0000, 0.4164]])


In [1]:
import torch
tensor1 = torch.randn(5, 5, 2)
result = tensor1[:, :, -1]
print(result)

/data/zhyma/miniconda3/lib/python3.8/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


tensor([[ 0.9276, -0.6224,  0.2619,  1.6807,  0.9850],
        [-0.7602, -1.5217,  0.4478,  0.8117, -1.5254],
        [-0.3378, -0.4417,  2.2237, -0.5816,  0.0990],
        [-2.2766, -0.5766,  0.3488,  0.2291, -0.7727],
        [ 0.4435, -0.4417,  2.4707,  0.8385,  1.3493]])


In [4]:
import torch

# 创建一个形状为 (3, 4, 5) 的随机 Tensor
x = torch.randn(3, 4, 5)

# 计算每一行中需要置为 1 的元素的数量
num_elements_to_set = x.shape[-1] // 2

# 获取每一行中最大的 num_elements_to_set 个元素的下标
top_k_values, top_k_indices = torch.topk(x, k=num_elements_to_set, dim=-1)

# 创建一个全为 0 的 mask Tensor
mask = torch.zeros_like(x)

# 将每一行中最大的 num_elements_to_set 个元素的下标对应的位置置为 1
mask.scatter_(dim=-1, index=top_k_indices, src=torch.ones_like(top_k_indices).to(mask.dtype))
print(x)
# 打印最终的 mask 01 矩阵
print(mask)


tensor([[[ 0.2270, -0.4146, -2.1177, -0.2306,  0.8834],
         [ 0.7782, -0.5131,  1.4310,  0.5452, -1.5131],
         [-0.6511,  0.7880, -0.8208, -0.7241, -0.8657],
         [ 1.8046,  0.6929, -0.1265, -1.2426,  0.4891]],

        [[ 1.7446, -0.1975, -0.5620, -0.2608, -0.6617],
         [-2.4954, -1.3500,  0.2372,  0.2050, -0.2221],
         [-0.7385, -0.9507, -0.4965,  1.3614, -1.8766],
         [-0.9451, -0.4799,  0.1365, -1.5041,  0.0132]],

        [[ 1.8013, -0.9333, -1.1561, -0.7110,  1.2781],
         [-0.0265, -0.0269, -0.8955,  2.1344,  0.3000],
         [ 0.4842, -0.5933, -0.5615, -0.5130,  1.8854],
         [ 0.0782,  0.3291,  0.3784,  1.1334, -0.0454]]])
tensor([[[1., 0., 0., 0., 1.],
         [1., 0., 1., 0., 0.],
         [1., 1., 0., 0., 0.],
         [1., 1., 0., 0., 0.]],

        [[1., 1., 0., 0., 0.],
         [0., 0., 1., 1., 0.],
         [0., 0., 1., 1., 0.],
         [0., 0., 1., 0., 1.]],

        [[1., 0., 0., 0., 1.],
         [0., 0., 0., 1., 1.],
        

In [5]:
import torch.nn.functional as F

# 定义一个随机张量
x = torch.randn(3, 4)

# 计算 softmax
y = F.softmax(x, dim=1)

print(y)


tensor([[0.4101, 0.3489, 0.2215, 0.0194],
        [0.5730, 0.1143, 0.2387, 0.0739],
        [0.4879, 0.2371, 0.0920, 0.1831]])
